version: "3.8"

services:
  discord-dash:
    build:
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile}
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - GENERAL_CHAT_ID=${GENERAL_CHAT_ID}
      - GEMINI_API_KEY=${GEMINI_API_KEY}